CREATE TABLE IF NOT EXISTS users
(
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(255)                            NOT NULL,
    email     VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT uq_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS category
(
    category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (category_id),
    CONSTRAINT uq_name UNIQUE (category_name)
);

CREATE TABLE IF NOT EXISTS event
(
    event_id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title              VARCHAR(120)                            NOT NULL,
    annotation         VARCHAR(2000),
    description        VARCHAR(7000),
    category_id        BIGINT                                  NOT NULL,
    event_date         TIMESTAMP WITH TIME ZONE                NOT NULL,
    paid               BOOLEAN                                 NOT NULL,
    request_moderation BOOLEAN                                 NOT NULL,
    created            TIMESTAMP WITH TIME ZONE                NOT NULL DEFAULT now(),
    published          TIMESTAMP WITH TIME ZONE,
    state              BIGINT                                  NOT NULL,
    initiator          BIGINT                                  NOT NULL,
    location_lat       DOUBLE PRECISION,
    location_lon       DOUBLE PRECISION,
    participant_limit  INT,
    CONSTRAINT pk_event PRIMARY KEY (event_id),
    CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES category,
    CONSTRAINT fk_initiator FOREIGN KEY (initiator) REFERENCES users
);

CREATE TABLE IF NOT EXISTS request
(
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id   BIGINT                                  NOT NULL,
    created    TIMESTAMP WITH TIME ZONE                NOT NULL DEFAULT now(),
    requester  BIGINT                                  NOT NULL,
    status     BIGINT                                  NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (request_id),
    CONSTRAINT fk_event FOREIGN KEY (event_id) REFERENCES event,
    CONSTRAINT fk_requester FOREIGN KEY (requester) REFERENCES users
);

CREATE TABLE IF NOT EXISTS compilation
(
    compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title          VARCHAR(255)                            NOT NULL,
    pinned         BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_compilation PRIMARY KEY (compilation_id)
);

CREATE TABLE IF NOT EXISTS event_compilation
(
    event_id       BIGINT,
    compilation_id BIGINT,
    CONSTRAINT fk_event_compilation FOREIGN KEY (event_id) REFERENCES event,
    CONSTRAINT fk_compilation FOREIGN KEY (compilation_id) REFERENCES compilation
);

CREATE TABLE IF NOT EXISTS comment
(
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text       VARCHAR(2000)                           NOT NULL,
    created    TIMESTAMP WITH TIME ZONE                NOT NULL DEFAULT now(),
    author     BIGINT                                  NOT NULL,
    status     BIGINT                                  NOT NULL,
    event_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (comment_id),
    CONSTRAINT fk_comment_event FOREIGN KEY (event_id) REFERENCES event,
    CONSTRAINT fk_author FOREIGN KEY (author) REFERENCES users
)

