CREATE TABLE IF NOT EXISTS stats
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app  VARCHAR(512)                            NOT NULL,
    uri  VARCHAR(512)                            NOT NULL,
    ip   VARCHAR(255)                            NOT NULL,
    time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);
